app/blueprints/dex/models.py
from app import db
from datetime import datetime

class Pokemon(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    name = db.Column(db.String(50), nullable=False)
    poke_num = db.Column(db.Integer, nullable=False)
    type1 = db.Column(db.String(50), nullable=False)
    type2 = db.Column(db.String(50))
    sprite = db.Column(db.String(1000), nullable=False)
    nickname = db.Column(db.String(50))
    description = db.Column(db.String(500))
    owner_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    owner = db.relationship('User', backref='pokemon')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

app = Flask(__name__)

app.config.from_object(Config)

db.init_app(app)
migrate.init_app(app, db)
login_manager.init_app(app)

from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)
from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)
from app.blueprints.dex import bp as dex_bp
app.register_blueprint(dex_bp)
from app.blueprints.api import bp as api_bp
app.register_blueprint(api_bp)

login_manager.login_view = 'auth.login'
login_manager.login_message = 'Access to this page requires being logged into an active account first.'
login_manager.login_message_category = 'danger'

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')

from . import routes

app/blueprints/api/routes.py
from . import bp
from flask import render_template
from app.blueprints.auth.models import User
from app.blueprints.dex.models import Pokemon

def name_filter(x):
    return x.name

def nick_filter(x):
    return x.nickname

@bp.route('/id/<id>')
def poke_by_id(id):
    poke = Pokemon.query.get(id)
    return render_template('poke-by-id.html.j2', poke=poke)

@bp.route('/owner/<username>')
def pokes_by_owner(username):
    owner = User.query.filter_by(username=username).first()
    pokes = Pokemon.query.filter_by(owner_id=owner.id).all()
    pokes.sort(key=nick_filter)
    pokes.sort(key=name_filter)
    return render_template('pokes-by-owner.html.j2', owner=owner, pokes=pokes)

app/blueprints/dex/__init__.py
from flask import Blueprint

bp = Blueprint('dex', __name__, url_prefix='/dex')

from . import routes,models

app/blueprints/dex/routes.py
from . import bp
from app import db
from flask import render_template, request, redirect, url_for, flash
from app.blueprints.auth.models import User
from app.blueprints.dex.models import Pokemon
from flask_login import current_user, login_required
import requests

def id_filter(x):
    return x.id

def name_filter(x):
    return x.name

def nick_filter(x):
    return x.nickname

@bp.route('/pokemon')
def pokemon():
    pokes = Pokemon.query.all()
    pokes.sort(key=id_filter)
    return render_template('pokemon.html.j2', pokes=pokes)

@bp.route('/pokemon/available')
@login_required
def available():
    pokes = Pokemon.query.filter_by(owner_id=None).all()
    pokes.sort(key=id_filter)
    return render_template('available.html.j2', pokes=pokes)

@bp.route('/collection')
@login_required
def collection():
    pokes = Pokemon.query.filter_by(owner_id=current_user.id).all()
    pokes.sort(key=nick_filter)
    pokes.sort(key=name_filter)
    return render_template('collection.html.j2', pokes=pokes)

@bp.route('/new_pokemon', methods=['GET', 'POST'])
def new_pokemon():
    if request.method == 'GET':
        return render_template('new-pokemon.html.j2')

    name = request.form['name'].lower()
    nickname = request.form['nickname']
    description = request.form['description']

    response = requests.get(f'https://pokeapi.co/api/v2/pokemon/{name}')

    if response.status_code == 200:
        data = response.json()

    else:
        flash(f'Oops! Looks like "{name}" is not a valid Pokémon. Please try again.', 'danger')
        return render_template('new-pokemon.html.j2')

    poke_num = data['id']
    type1 = data['types'][0]['type']['name']
    if len(data['types']) == 2:
        type2 = data['types'][1]['type']['name']

    else:
        type2 = None
    sprite = data['sprites']['front_default']

    new_poke = Pokemon(name=name, poke_num=poke_num, type1=type1, type2=type2, sprite=sprite, nickname=nickname, description=description, owner_id=None)
    db.session.add(new_poke)
    db.session.commit()
    if nickname == '':
        flash(f'{name.title()} added successfully!', 'success')

    else:
        flash(f'{nickname} added successfully!', 'success')

    return redirect(url_for('dex.pokemon'))

@bp.route('/collect', methods=['POST'])
@login_required
def collect():
    id = request.form['collectID']
    caught = Pokemon.query.filter_by(id=id).first()
    if caught.owner_id == None:
        caught.owner_id = current_user.id
        db.session.commit()
        if caught.nickname == '':
            flash(f'{caught.name.title()} collected successfully!', 'success')

        else:
            flash(f'{caught.nickname} collected successfully!', 'success')

    else:
        flash(f'Oops! Looks like that Pokémon already has an owner.', 'danger')
        return redirect(url_for('dex.available'))

    return redirect(url_for('dex.collection'))

@bp.route('/release', methods=['POST'])
@login_required
def release():
    id = request.form['releaseID']
    released = Pokemon.query.filter_by(id=id).first()
    if released.owner_id == current_user.id:
        released.owner_id = None
        db.session.commit()
        if released.nickname == '':
            flash(f'{released.name.title()} released successfully!', 'success')

        else:
            flash(f'{released.nickname} released successfully!', 'success')

    else:
        flash(f'Oops! Looks like you are not the owner of this Pokémon, so you are not permitted to release this one.', 'danger')
        return redirect(url_for('dex.collection'))

    return redirect(url_for('dex.available'))

@bp.route('/rename', methods=['POST'])
@login_required
def rename():
    id = request.form['renameID']
    renamed = Pokemon.query.filter_by(id=id).first()
    old_nick = renamed.nickname
    new_nick = request.form['newNick']

    if renamed.owner_id == current_user.id:
        renamed.nickname = new_nick
        db.session.commit()
        if old_nick == '':
            flash(f'{renamed.name.title()} was renamed successfully to {renamed.nickname}!', 'success')
        else:
            flash(f'{old_nick} was renamed successfully to {renamed.nickname}!', 'success')
    else:
        flash(f'Oops! Looks like you are not the owner of this Pokémon, so you are not permitted to rename this one.', 'danger')
        return redirect(url_for('dex.collection'))

    return redirect(url_for('dex.collection'))

@bp.route('/redescribe', methods=['POST'])
@login_required
def redesc():
    id = request.form['redescID']
    redesced = Pokemon.query.filter_by(id=id).first()
    new_desc = request.form['newDesc']

    if redesced.owner_id == current_user.id:
        redesced.description = new_desc
        db.session.commit()
        if redesced.nickname == '':
            flash(f'{redesced.name.title()} has a new description!', 'success')

        else:
            flash(f'{redesced.nickname} has a new description!', 'success')
            
    else:
        flash(f'Oops! Looks like you are not the owner of this Pokémon, so you are not permitted to give this one a new description.', 'danger')
        return redirect(url_for('dex.collection'))

    return redirect(url_for('dex.collection'))

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='/')

from . import routes

app/blueprints/main/routes.py
from . import bp
from flask import render_template
from flask_login import login_required

@bp.route('/')
@login_required
def home():
    return render_template('home.html.j2')

@bp.route('/about')
def about():
    return render_template('about.html.j2')

app/templates/about.html.j2
{% extends './layout.html.j2' %}

{% block title %}About{% endblock title %}

{% block content %}
    <h1>Gotta Catch 'Em All</h1>
    <br>
    <p class="fs-4 mx-5">"I wanna be the very best. Like no one ever was. To catch them is my real test. To train them is my cause. I will travel across the land. Searching far and wide. Teach Pokémon to understand. The power that's inside. Pokémon! Gotta catch 'em all!. It's you and me. I know it's my destiny. Pokémon! Oh, you're my best friend. In a world we must defend. Pokémon! Gotta catch 'em all! A heart so true. Our courage will pull us through. You teach me and I'll teach you. Ooh, ooh. Pokémon! Gotta catch 'em all! Gotta catch 'em all! Yeah! Every challenge along the way. With courage, I will face. I will battle every day. To claim my rightful place. Come with me, the time is right. There's no better team. Arm in arm, we'll win the fight. It's always been our dream. Pokémon! Gotta catch 'em all! It's you and me. I know it's my destiny. Pokémon! Oh, you're my best friend. In a world we must defend. Pokémon! Gotta catch 'em all! A heart so true. Our courage will pull us through. You teach me and I'll teach you. Ooh, ooh. Pokémon! Gotta catch 'em all! Gotta catch 'em all! Gotta catch 'em all! Gotta catch 'em all! Gotta catch 'em all! Yeah! Pokémon! Gotta catch 'em all! It's you and me. I know it's my destiny. Pokémon! Oh, you're my best friend. In a world we must defend Pokémon! Gotta catch 'em all! A heart so true. Our courage will pull us through. You teach me and I'll teach you. Ooh, ooh. Pokémon! Gotta catch 'em all! Gotta catch 'em all! Pokémon!"</p>
{% endblock content %}

app/templates/available.html.j2
{% extends './layout.html.j2' %}

{% block title %}Available Pokémon{% endblock title %}

{% block content %}
<h1>Available Pokémon</h1>
<br>
<div class="container text-center">
    <div class="row row-cols-3 justify-content-between">
        {% for poke in pokes %}
            <div class="border-5 py-3">
                    <div class="col card border-warning py-5">
                {% if poke.nickname != '' %}
                    <h3>{{ poke.nickname }} ({{ poke.name.title() }})</h3>
                {% else %}
                    <h3>{{ poke.name.title() }}</h3>
                {% endif %}
                <h5>ID # {{ poke.id }}</h5>
                <div class="px-5">
                    <img src="{{ poke.sprite }}" alt="{{ poke.name }} sprite">
                    <p>Pokémon #: {{ poke.poke_num }}</p>
                    <p>Type 1: {{ poke.type1.title() }}</p>
                    {% if poke.type2 == None %}
                        <p>Type 2: None</p>
                    {% else %}
                        <p>Type 2: {{ poke.type2.title() }}</p>
                    {% endif %}
                    {% if poke.description == '' %}
                        <p>Description: None</p>
                    {% else %}
                        <p>Description: {{ poke.description }}</p>
                    {% endif %}
                    <p>Date Entered: {{ poke.date_created }}</p>
                
                <br>
                <form action="{{ url_for('dex.collect') }}" method="POST">
                    <input type="hidden" class="form-control" id="collectID" name="collectID" value="{{ poke.id }}">
                    {% if poke.nickname != '' %}
                        <button type="submit" class="btn btn-primary">Collect {{ poke.nickname }}</button>
                    {% else %}
                        <button type="submit" class="btn btn-primary">Collect {{ poke.name.title() }}</button>
                    {% endif %}
                </form>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}

app/templates/collection.html.j2
{% extends './layout.html.j2' %}

{% block title %}Your Collection{% endblock title %}

{% block content %}
<h1>Your Pokémon Collection</h1>
<br>
<div class="container text-center">
    <div class="row row-cols-3 justify-content-between">
        {% for poke in pokes %}
            <div class="border-5 py-3">
                <div class="col card border-warning py-5">
                    {% if poke.nickname != '' %}
                        <h3>{{ poke.nickname }} ({{ poke.name.title() }})</h3>
                    {% else %}
                        <h3>{{ poke.name.title() }}</h3>
                    {% endif %}
                    <h5>ID # {{ poke.id }}</h5>
                    <div class="px-5">
                        <img src="{{ poke.sprite }}" alt="{{ poke.name }} sprite">
                        <p>Pokémon #: {{ poke.poke_num }}</p>
                        <p>Type 1: {{ poke.type1.title() }}</p>
                        {% if poke.type2 == None %}
                            <p>Type 2: None</p>
                        {% else %}
                            <p>Type 2: {{ poke.type2.title() }}</p>
                        {% endif %}
                        {% if poke.description == '' %}
                            <p>Description: None</p>
                        {% else %}
                            <p>Description: {{ poke.description }}</p>
                        {% endif %}
                        <p>Date Entered: {{ poke.date_created }}</p>
                    <br>
                    <form action="{{ url_for('dex.rename') }}" method="POST">
                        <input type="hidden" class="form-control" id="renameID" name="renameID" value="{{ poke.id }}">
                        <div class="mb-3">
                            <label for="newNick" class="form-label">New Nickname</label>
                            <input type="text" class="form-control border-warning" id="newNick" name="newNick">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    <br><hr><br>
                    <form action="{{ url_for('dex.redesc') }}" method="POST">
                        <input type="hidden" class="form-control" id="redescID" name="redescID" value="{{ poke.id }}">
                        <div class="mb-3">
                            <label for="newDesc" class="form-label">New Description</label>
                            <input type="text" class="form-control border-warning" id="newDesc" name="newDesc">
                            <div id="descHelp" class="form-text">(Max. 500 characters)</div>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    <br><hr><br>
                    <form action="{{ url_for('dex.release') }}" method="POST">
                        <input type="hidden" class="form-control" id="releaseID" name="releaseID" value="{{ poke.id }}">
                        {% if poke.nickname != '' %}
                            <button type="submit" class="btn btn-danger">Release {{ poke.nickname }}</button>
                        {% else %}
                            <button type="submit" class="btn btn-danger">Release {{ poke.name.title() }}</button>
                        {% endif %}
                    </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

app/templates/hint.html.j2
{% extends './layout.html.j2' %}

{% block title %}Password Hint{% endblock title %}

{% block content %}
    <h1>Your Password Hint:</h1>
    <h3 class="mt-5 ms-5">"{{ current_user.pw_hint }}"</h3>
{% endblock content %}

app/templates/home.html.j2
{% extends './layout.html.j2' %}

{% block title %}PokéHome{% endblock title %}

{% block content %}
    <h1>PokéHome </h1>
    <br>
    <div class="d-grid col-3 px-4 mx-4 gap-4">
        <a href="{{ url_for('dex.new_pokemon') }}" class="btn btn-primary btn-lg">Add a New Pokémon to Available</a>
        <a href="{{ url_for('dex.pokemon') }}" class="btn btn-primary btn-lg">All Pokémon</a>
        <a href="{{ url_for('dex.available') }}" class="btn btn-primary btn-lg">Available Pokémon</a>
        <a href="{{ url_for('dex.collection') }}" class="btn btn-primary btn-lg">Your Pokémon Collection</a>
    </div>
{% endblock content %}

app/templates/layout.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>
<body>
    <header class="mb-5">
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark mb-5" style="background-color: #cc0000;">
                <div class="container-fluid">
                    <a class="navbar-brand px-5 fs-2" href="{{ url_for('main.home') }}">PokéDexter</a>
                    
                    <div class="collapse navbar-collapse fs-5" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 gap-3">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('dex.new_pokemon') }}">New Pokémon</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('dex.pokemon') }}">All Pokémon</a>
                            </li>
                            {% if not current_user.is_anonymous %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('dex.available') }}">Available Pokémon</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('dex.collection') }}">Your Collection</a>
                                </li>
                            {% endif %}
                        </ul>

                        <ul class="navbar-nav mb-2 mb-lg-0">
                        {% if current_user.is_anonymous %}
                            <li class="nav-item mx-3">
                                <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                            </li>
                            <li class="nav-item mx-3">
                                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                            </li>
                        {% else %}
                            <li class="nav-item mx-3">
                                <a class="nav-link">Logged in as: <strong>{{ current_user.username }}</strong></a>
                            </li>
                            <li class="nav-item mx-3">
                                <a class="nav-link" href="{{ url_for('auth.reset_password') }}">Password Reset</a>
                            </li>
                            <li class="nav-item mx-3">
                                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                            </li>
                        {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
    </header>

    <main class="container mt-5 pt-5">
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                <div class=flashes>
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock content %}
    </main>
</body>
</html>

app/templates/login.html.j2
{% extends './layout.html.j2' %}

{% block title %}Login{% endblock title %}

{% block content %}
    <h1>Login</h1>
    <br>
    <div class="row justify-content-evenly">
        {# START LOGIN W/ USERNAME #}
        <form class="card col-5 py-4 px-5" action="{{ url_for('auth.login_username') }}" method="POST">
            {# NEXT PAGE LINE #}
            <input type="hidden" name="next" value="{{ request.args.get('next', '') }}">
            <h3>Login With Your Username</h3>
            <div class="mb-3 mt-4">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>
            <div class="mb-4">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <button class="btn btn-primary mt-3 mb-4" type="submit">Submit</button>
        </form>
        {# END LOGIN W/ USERNAME #}
        <br><br>
        {# START LOGIN W/ EMAIL #}
        <form class="card col-5 py-4 px-5" action="{{ url_for('auth.login_email') }}" method="POST">
            {# NEXT PAGE LINE #}
            <input type="hidden" name="next" value="{{ request.args.get('next', '') }}">
            <h3><strong>OR</strong> Login With Your Email Address</h3>
            <div class="mb-3 mt-4">
                <label for="email" class="form-label">Email address</label>
                <input type="email" class="form-control" id="email" name="email">
            </div>
            <div class="mb-4">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <button class="btn btn-primary mt-3 mb-4" type="submit">Submit</button>
        </form>
        {# END LOGIN W/ EMAIL #}
    </div>
    <p class="mt-4 ms-5">Need to sign up for an account? <a href="{{ url_for('auth.register') }}"><strong>CLICK HERE</strong></a></p>
{% endblock content %}

app/templates/new-pokemon.html.j2
{% extends './layout.html.j2' %}

{% block title %}Add a New Pokémon{% endblock title %}

{% block content %}
<h1>Add a New Pokémon to Available</h1>
<br>
<form action="{{ url_for('dex.new_pokemon') }}" method="POST">
    <div class="mb-3">
        <label for="name" class="form-label fs-4">Pokéname</label>
        <div id="nameHelp" class="form-text  fs-6">(Examples: pikachu, snorlax, charizard)</div>
        <input type="text" class="form-control" id="name" name="name">
    </div>
    <div class="mb-3">
        <label for="nickname" class="form-label fs-4">Nickname</label>
        <input type="text" class="form-control" id="nickname" name="nickname">
    </div>
    <div class="mb-3">
        <label for="description" class="form-label fs-4">Description</label>
        <input type="text" class="form-control" id="description" name="description">
    </div>
    <br>
    <button type="submit" class="btn btn-primary fs-4">Submit</button>
</form>
{% endblock content %}

app/templates/poke-by-id.html.j2
{% extends './layout.html.j2' %}

{% block title %}Pokémon ID # {{ poke.id }}{% endblock title %}

{% block content %}
    {% if poke.nickname != '' %}
        <h3>{{ poke.nickname }} ({{ poke.name.title() }})</h3>
    {% else %}
        <h3>{{ poke.name.title() }}</h3>
    {% endif %}
    <h2>{{ poke.year }} {{ poke.make }} {{ poke.model }}</h2>
    <br>
    <h5>ID # {{ poke.id }}</h5>
    <div class="px-5">
        <img src="{{ poke.sprite }}" alt="{{ poke.name }} sprite">
        <p>Pokémon #: {{ poke.poke_num }}</p>
        <p>Type 1: {{ poke.type1.title() }}</p>
        {% if poke.type2 == None %}
            <p>Type 2: None</p>
        {% else %}
            <p>Type 2: {{ poke.type2.title() }}</p>
        {% endif %}
        {% if poke.description == '' %}
            <p>Description: None</p>
        {% else %}
            <p>Description: {{ poke.description }}</p>
        {% endif %}
        {% if poke.owner_id == None %}
            <p>=~=~= This Pokémon is currently unowned. =~=~=</p>
        {% else %}
            <p>Owner: {{ poke.owner.username }} ({{ poke.owner.first_name }} {{ poke.owner.last_name }})</p>
        {% endif %}
        <p>Date Entered: {{ poke.date_created }}</p>
    </div>
{% endblock content %}

app/templates/pokemon.html.j2
{% extends './layout.html.j2' %}

{% block title %}All Pokémon{% endblock title %}

{% block content %}
<h1>All Pokémon</h1>
<br>
<div class="container text-center">
    <div class="row row-cols-3 justify-content-between">
        {% for poke in pokes %}
            <div class="border-5 py-3">
                <div class="col card border-warning py-5">
                    {% if poke.nickname != '' %}
                        <h3>{{ poke.nickname }} ({{ poke.name.title() }})</h3>
                    {% else %}
                        <h3>{{ poke.name.title() }}</h3>
                    {% endif %}
                    <h5>ID # {{ poke.id }}</h5>
                    <div class="px-5">
                        <img src="{{ poke.sprite }}" alt="{{ poke.name }} sprite">
                        <p>Pokémon #: {{ poke.poke_num }}</p>
                        <p>Type 1: {{ poke.type1.title() }}</p>
                        {% if poke.type2 == None %}
                            <p>Type 2: None</p>
                        {% else %}
                            <p>Type 2: {{ poke.type2.title() }}</p>
                        {% endif %}
                        {% if poke.description == '' %}
                            <p>Description: None</p>
                        {% else %}
                            <p>Description: {{ poke.description }}</p>
                        {% endif %}
                        {% if poke.owner_id == None %}
                            <p>=~=~= Currently Unowned =~=~=</p>
                        {% else %}
                            <p>Owner: {{ poke.owner.username }} ({{ poke.owner.first_name }} {{ poke.owner.last_name }})</p>
                        {% endif %}
                        <p>Date Entered: {{ poke.date_created }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

app/templates/pokes-by-owner.html.j2
{% extends './layout.html.j2' %}

{% block title %}{{ owner.username }}'s Pokémon{% endblock title %}

{% block content %}
    <h1>{{ owner.username }}'s Pokémon</h1>
    <hr>
    {{ owner.first_name }} currently owns {{ pokes | length }} Pokémon.
    <br><hr><br>
    <div class="container text-center">
        <div class="row row-cols-3 justify-content-between">
            {% for poke in pokes %}
                <div class="border-5 py-3">
                    <div class="col card border-warning py-5">
                        {% if poke.nickname != '' %}
                            <h3>{{ poke.nickname }} ({{ poke.name.title() }})</h3>
                        {% else %}
                            <h3>{{ poke.name.title() }}</h3>
                        {% endif %}
                        <h2>{{ poke.year }} {{ poke.make }} {{ poke.model }}</h2>
                        <br>
                        <h5>ID # {{ poke.id }}</h5>
                        <div class="px-5">
                            <img src="{{ poke.sprite }}" alt="{{ poke.name }} sprite">
                            <p>Pokémon #: {{ poke.poke_num }}</p>
                            <p>Type 1: {{ poke.type1.title() }}</p>
                            {% if poke.type2 == None %}
                                <p>Type 2: None</p>
                            {% else %}
                                <p>Type 2: {{ poke.type2.title() }}</p>
                            {% endif %}
                            {% if poke.description == '' %}
                                <p>Description: None</p>
                            {% else %}
                                <p>Description: {{ poke.description }}</p>
                            {% endif %}
                            {% if poke.owner_id == None %}
                                <p>=~=~= This Pokémon is currently unowned. =~=~=</p>
                            {% else %}
                                <p>Owner: {{ poke.owner.username }} ({{ poke.owner.first_name }} {{ poke.owner.last_name }})</p>
                            {% endif %}
                            <p>Date Entered: {{ poke.date_created }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

app/templates/reset-password.html.j2
{% extends './layout.html.j2' %}

{% block title %}Password Reset{% endblock title %}

{% block content %}
<h1>Reset Your Password</h1>
<br>
<p><strong>*</strong> denotes a required field</p>
<p>Reminder: Passwords ARE case-sensitive!</p>
<form action="{{ url_for('auth.reset_password') }}" method="POST">
    <div class="mb-3 mt-4">
        <label for="currPass" class="form-label fs-4">Current Password<strong>*</strong></label>
        <input type="password" class="form-control" id="currPass" name="currPass">
        <div id="passHelp" class="form-text ms-2"><a href="{{ url_for('auth.hint') }}" target="_blank">(Click here if you'd like to view your password hint.)</a></div>
    </div>
    <div class="mb-3">
        <label for="newPass" class="form-label fs-4">New Password<strong>*</strong></label>
        <input type="password" class="form-control" id="newPass" name="newPass">
    </div>
    <div class="mb-3">
        <label for="confirmNew" class="form-label fs-4">Confirm New Password<strong>*</strong></label>
        <input type="password" class="form-control" id="confirmNew" name="confirmNew">
    </div>
    <div class="mb-5">
        <label for="passHint" class="form-label fs-4">New Password Hint</label>
        <input type="text" class="form-control" id="passHint" name="passHint">
    </div>
    <button type="submit" class="btn btn-primary fs-4">Submit</button>
</form>
{% endblock content %}